---
abstract: 'RRD Graph View Class'
author:
  - 'Jose Luis Martinez (jlmartinez@capside.com)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 0
  Test::Simple: 0.44
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.950'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-RRDGraph
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Static::Simple: 0.17
  Catalyst::Runtime: 0
  MRO::Compat: 0
  RRDs: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
