# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Server-Mail-ESMTP-SIZE
version:      0.01
version_from: lib/Net/Server/Mail/ESMTP/SIZE.pm
installdirs:  site
requires:
    Net::Server::Mail:             0.13
    Test::Simple:                  0.44
    Test::SMTP:                    0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
