--- #YAML:1.0
name:                Catalyst-Authentication-Credential-Authen-Simple
version:             0.01
abstract:            Verify credentials with the Authen::Simple framework
license:             perl
author:              
    - Jose Luis Martinez (jlmartinez@capside.com)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Authen::Simple:                0
    Catalyst::Plugin::Authentication: >= 1.0
    Catalyst::Runtime:             0
    Module::Load:                  0
    Test::More:                    0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
