# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Nagios-Plugin-DieNicely
version:      0.01
version_from: lib/Nagios/Plugin/DieNicely.pm
installdirs:  site
requires:
    Test::More:                    0.62
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
